Changes to the incremental responses
apollo-server-integrations/apollo-server-integration-next pull request #204
Opened 2024-07-19 19:24 UTC by jer-k

Fixes: https://github.com/apollo-server-integrations/apollo-server-integration-next/issues/203

Preface: This is my first exposure to working with these Node objects on the server side so I'm not entirely sure if what I've done is correct.

I changed the way the incremental responses are sent back to the client. In the issue I noted 

```
      for await (const chunk of httpGraphQLResponse.body.asyncIterator) {
        body.push(chunk);
      }
```

this `await` is stopping the server from incrementally delivering the responses and instead they're all delivered at once.

These changes allow the responses to be streamed back instead of all at once. 

The logs in the client now show
```
what is data? {book: {…}} false 12:22:18
what is data? {book: {…}} false 12:22:19
```

Where the second `book: {}` has the deferred data and is delivered 1 second after the first in which the 1 second is hard coded in my project using this package.

2024-07-19 19:26 UTC, jer-k commented
A couple things I've noticed. With these changes the `Preview` and `Response` panes in the Chrome DevTools aren't showing any data even though the response is working

![image](https://github.com/user-attachments/assets/2dc5a16b-10e8-4220-abc8-0d467ded99fe)
![image](https://github.com/user-attachments/assets/c0e8af2e-30bb-4d51-b133-017dcb4ab0a3)
![image](https://github.com/user-attachments/assets/efa712d4-4a60-47d1-b008-de45a4260cf0)

I'm guessing something I've changed messed this up.

2024-07-19 19:28 UTC, jer-k commented on src/startServerAndCreateNextHandler.ts
> +          'Content-Type': 'multipart/mixed; boundary="-"',
If this header isn't set, then Apollo Client throws an error that looks like this

`Error: No number after minus sign in JSON at position 3 (line 2 column 2)`

Looking at the data being sent, it lines up with the `---`
![image](https://github.com/user-attachments/assets/3ed0d45e-2e1e-47f0-8967-2fce8742fd3a)

2024-07-19 21:37 UTC, jer-k commented on src/startServerAndCreateNextHandler.ts
> +          'Content-Type': 'multipart/mixed; boundary="-"',
I fixed this by ensuring the passed in headers are applied in all cases

2024-07-23 15:41 UTC, martinnabhan commented
Thank you for the thorough explanation! I'll try to take a closer look this week.

2024-07-29 10:48 UTC, martinnabhan requested changes
I've added some suggestions! Could you also remove `noIncrementalDelivery: true` from `src/__tests__/integration.test.ts` so we make sure to test incremental delivery as well?

I also noticed Chrome's `Preview` and `Response` panes aren't showing any data but I think that's normal for multipart responses.

2024-07-29 10:48 UTC, martinnabhan commented on src/startServerAndCreateNextHandler.ts
> +    }
Since `headers` isn't used in the `if (isNextApiRequest(req))` code block it would be better to move this below the if statement.

2024-07-29 10:48 UTC, martinnabhan commented on src/startServerAndCreateNextHandler.ts
> +        res.writeHead(200, headers);
I don't think this is necessary if we use `res.send` below.

2024-07-29 10:48 UTC, martinnabhan commented on src/startServerAndCreateNextHandler.ts
> +        },
I think it's more common to use pull, and then use the iterator without looping like this:
```suggestion
        async pull(controller) {
          if (httpGraphQLResponse.body.kind === 'chunked') {
            const { value, done } = await httpGraphQLResponse.body.asyncIterator.next();
        
            if (done) {
              controller.close();
            } else {
              controller.enqueue(value);
            }
          }
        },
```

2024-07-29 10:48 UTC, martinnabhan commented on src/startServerAndCreateNextHandler.ts
>          res.send(httpGraphQLResponse.body.string);
After supporting incremental responses we have to move `res.end()` to here so we don't end the response prematurely:
```suggestion
        res.send(httpGraphQLResponse.body.string);
        res.end();
```

2024-07-29 10:48 UTC, martinnabhan commented on src/startServerAndCreateNextHandler.ts
>          for await (const chunk of httpGraphQLResponse.body.asyncIterator) {
We should support incremental responses for API routes as well. We can just replace the for loop with this:
```ts
res.send(Readable.from(httpGraphQLResponse.body.asyncIterator));
```

2024-07-29 10:48 UTC, martinnabhan commented on src/startServerAndCreateNextHandler.ts
> +    let responseObject: string | ReadableStream;
I would prefer if we could use a ternary instead of a re-assignable variable, like this:
```ts
    return new Response(
      httpGraphQLResponse.body.kind === 'complete'
        ? httpGraphQLResponse.body.string
        : new ReadableStream({ ... }),
      { headers, status: httpGraphQLResponse.status || 200 },
    );
```

2024-07-29 15:08 UTC, jer-k commented
Thank you for all the feedback! It is a much cleaner implementation.

On the Preview panel, there definitely is some way for the data to show up. This screenshot is from my work's application, which uses Apollo Client + graphql-ruby. I'll spend some time this morning and see if I can't uncover any information as to what is going on

![image](https://github.com/user-attachments/assets/d51af2f7-1a92-4f89-98cc-4835ceffd97a)

2024-07-30 15:27 UTC, jer-k commented
Okay I figured it out and I believe it is an upstream issue in Apollo Server and improperly setting the header.

```
what are raw headers? HeaderMap(2) [Map] {
  'cache-control' => 'no-store',
  'content-type' => 'multipart/mixed; boundary="-"; deferSpec=20220824',
  __identity: Symbol(HeaderMap)
}
```

When the headers are written in and the `deferSpec=20220824',` portion is retained, we do not get the Preview response.

I changed the code to

```
    const headers: Record<string, string> = {
      'content-type': 'multipart/mixed; boundary="-"',
    };
    // console.log('what are raw headers?', httpGraphQLResponse.headers);
    // for (const [key, value] of httpGraphQLResponse.headers) {
    //   headers[key] = value;
    // }
```

And the preview correctly displays
![image](https://github.com/user-attachments/assets/afdf6335-d0a8-438c-b41d-3d3be4cd7e22)

2024-07-31 01:14 UTC, martinnabhan approved these changes

2024-07-31 01:28 UTC, martinnabhan commented
Thank you for looking into this. I don't think we want to change any headers coming from Apollo Server, so I'll go ahead and add a changeset and release this as is.

Thank you for the pull request!

2024-07-31 01:28 UTC, merged